// <auto-generated> — generado por tools/generate_spotdiff.py. No editar a mano.
namespace BrainTrain.App.Core.Minigames;

/// <summary>Centro normalizado (0..1) de una diferencia. El radio de acierto lo define el motor.</summary>
public readonly record struct DiffPoint(double X, double Y);

public sealed record SpotDiffScene(string Name, string ImageA, string ImageB, IReadOnlyList<DiffPoint> Diffs);

public static class SpotDiffScenes
{
    public static readonly IReadOnlyList<SpotDiffScene> All =
    [
        new("Parque", "spotdiff1a.png", "spotdiff1b.png", [new(0.1250, 0.1771), new(0.2597, 0.5979), new(0.6250, 0.5417), new(0.8611, 0.4125), new(0.5417, 0.8333)]),
        new("Playa", "spotdiff2a.png", "spotdiff2b.png", [new(0.8889, 0.1458), new(0.3639, 0.5583), new(0.2292, 0.8500), new(0.6944, 0.6875), new(0.1250, 0.8125)]),
        new("Espacio", "spotdiff3a.png", "spotdiff3b.png", [new(0.2083, 0.2708), new(0.8333, 0.1875), new(0.5000, 0.4500), new(0.8000, 0.7125), new(0.1833, 0.7667)]),
    ];
}
